###############################################################################
# Database configuration

# Connection string is in Go pq driver format:
# host=<host> port=<port> user=<databaseUser> password=<databaseUserPassword> dbname=<databaseName>

[database]

# db host for docker-compose
connection_string = "host=big-data-fina-project-db-12906.7tt.cockroachlabs.cloud port=26257 user=cu_student password=h2Cm9VhSEiomWMZRFE4rAg dbname=jobs_db"
max_idle_connections = 5
max_open_connections = 20
connection_max_lifetime = "60s"
driver_name = "postgres"
###############################################################################
# HTTP server configuration

[http]

server_address = ":8081"
server_url = "api.constructopedia.app"
###############################################################################
# RabbitMQ configuration

[rabbitmq]

rabbitmq_instance_type = "publisher"
rabbitmq_url = "amqp://guest:guest@localhost:5672/"
###############################################################################
# Geocoder API configuration

[geocoder]

geocoder_api_key="AIzaSyCdZebGh7LnvVq5cINvbSlYupdykRlANw4"

###############################################################################
# CORS configuration

[cors]

allowed_origins = ["*"]
allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]