###############################################################################
# Database configuration

# Connection string is in Go pq driver format:
# host=<host> port=<port> user=<databaseUser> password=<databaseUserPassword> dbname=<databaseName>

[database]

# db host for docker-compose
connection_string = "big-data-final-project-db.cnncnbpar4dt.us-west-2.rds.amazonaws.com"
max_idle_connections = 5
max_open_connections = 20
connection_max_lifetime = "60s"
driver_name = "postgres"
###############################################################################
# HTTP server configuration

[http]

server_address = ":8081"
###############################################################################
# RabbitMQ configuration

[rabbitmq]

rabbitmq_instance_type = "publisher"
rabbitmq_url = "amqp://guest:guest@localhost:5672/"
###############################################################################
# Geocoder API configuration

[geocoder]

geocoder_api_key="AIzaSyCdZebGh7LnvVq5cINvbSlYupdykRlANw4"

###############################################################################
# CORS configuration

[cors]

allowed_origins = ["*"]
allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]