apiVersion: v1
kind: Service
metadata:
  name: jobs-app-service
spec:
  selector:
    app: jobs-app
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
