apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs-app
spec:
  selector:
    matchLabels:
      app: jobs-app
  replicas: 1
  template:
    metadata:
      labels:
        app: jobs-app
    spec:
      containers:
        - image: jobs-app:latest
          name: jobs-app
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: ENV
              value: "k8s"